export const MOCK_HISTORY = [
  {
    id: "1",
    Produto: "Apresuntado",
    Quantidade: "10 unidades",
    Modalidade: "Saida",
    Preço: "R$12,00",
    Lote: "12123",
    Sigla: "APRFE",
    DataHora: "30.01.2024 - 22:10",
    Autor: "Caio Vinicius",
  },
  {
    id: "2",
    Produto: "Queijo",
    Quantidade: "9 unidades",
    Modalidade: "Entrada",
    Preço: "R$8,00",
    Lote: "14323",
    Sigla: "QUEGTRS",
    DataHora: "31.01.2024 - 07:54",
    Autor: "Jose Vinicius",
  },
  {
    id: "3",
    Produto: "Nuggets",
    Quantidade: "5 unidades",
    Modalidade: "Saida",
    Preço: "R$5,00",
    Lote: "98765",
    Sigla: "ARZSM",
    DataHora: "01.02.2024 - 14:30",
    Autor: "Maria Oliveira",
  },
  {
    id: "4",
    Produto: "HotPocket",
    Quantidade: "8 unidades",
    Modalidade: "Entrada",
    Preço: "R$3,50",
    Lote: "65432",
    Sigla: "MCRRN",
    DataHora: "02.02.2024 - 10:15",
    Autor: "Carlos Silva",
  },
  {
    id: "5",
    Produto: "Empanado",
    Quantidade: "12 unidades",
    Modalidade: "Saida",
    Preço: "R$2,50",
    Lote: "87654",
    Sigla: "LEITEX",
    DataHora: "03.02.2024 - 18:45",
    Autor: "Ana Rodrigues",
  },
];
