export const TRANSLATION = {
  type: "Tipo",
  quantity: "Quantidade",
  inventoryLot: "Lote",
  inventoryProduct: "Produto",
  createdAt: "Data/Hora",
  customerName: "Cliente",
  customerPaymentType: "Forma de pagamento",
  createdBy: "Autor",
  validity: "Validade",
  price: "Preço",
  name: "Nome",
  lot: "Lote",
  productName: "Produto",
  role: "Cargo",
};
export const TRANSLATION_VALUE = {
  input: "Entrada",
  output: "Saída",
  "credit-card": "Cartão de Crédito",
  pix: "pix",
  "debit-card": "Cartão de Débito",
  prazo: "Prazo",
  money: "Dinheiro",
};
